name: Create Release and Publish

on:
  push:
    branches: [main]

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: |
          npm install
          npm test
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            package.json

  release:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.package-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: package-version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if git ls-remote --exit-code --tags origin "v$VERSION"; then
            echo "Version v$VERSION already exists"
            exit 1
          fi
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.package-version.outputs.version }}
          release_name: Release v${{ steps.package-version.outputs.version }}
          draft: false
          prerelease: false

  publish:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    strategy:
      matrix:
        registry:
          - { url: "https://registry.npmjs.org", token: "NPM_TOKEN" }
          - { url: "https://npm.pkg.github.com", token: "GITHUB_TOKEN" }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: ${{ matrix.registry.url }}
          scope: "@quail-ai"
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets[matrix.registry.token] }}
